### ISSUE TITLE
Improvement: please filter users starting with "_" out from the users list

### ISSUE THREAD

**Issue by fibbs** [freeella/logoutd#1]
Example:

{
      "locked" : false,
      "username" : "_mbsetupuser",
      "active" : false
    }

This appears at one of my systems some times. No kid will ever have a user name like this, so please filter them out at the agent.

**Comment by freeella** [comment]
commit b43f18131dea65778d4e82660def60b3b5c8e8dc
    ignore system users according to Issue 1: Improvement: please filter users starting with _ out from the users list #1
