### ISSUE TITLE
Improvement: output user's REAL NAME additional to the username

### ISSUE THREAD

**Issue by fibbs** [freeella/logoutd#2]
At the moment, a request for all users (/status) gives me the user name, locked and active state of all interactive users. Additionally to that, I would like to see the user's Real Name (i. e. "Karl Musterhauser") for nicer GUI building.

**Comment by freeella** [comment]
New output will be:

```
# ./logoutd_test.bash
+ wget '--header=Content-Type: application/json' -t 1 -qO - http://127.0.0.1:8083/edward/api/v1.0/status
{
  "users": [
    {
      "fullname": "Some User",
      "screen_active": true,
      "screen_locked": "not_yet_implemented",
      "user_disabled": false,
      "username": "someuser"
    }
  ]
}#
```

**Comment by freeella** [comment]
commit bf3290beb3dbb407bf5fced7ba0b7a07e685e74e
    fixed witespace issue in finger regex

commit 817b4fb26aa62e1844852c6161ff3d592bbad017
    Implemented issue 2: Improvement: output user's REAL NAME additional to the username #2
